####################################
#     SCENARIO CONFIGURATION       #
####################################

[scenario]
    year = 2015
    verify = false
    landuse_file = "inputs/landuse/tazData.csv"
    landuse_index_column = "ZONE"
    landuse_index_in_network_column = "@taz_id"
    landuse_total_population_column = "TOTPOP"
    landuse_total_employment_column ="TOTEMP"
    landuse_total_acre_column = "TOTACRE"

[run]
    start_component = ""
    initial_components = [
        #"create_tod_scenarios",
        #"home_accessibility",
        #"prepare_network_highway",
        #"highway",
        #"prepare_network_transit",
        #"transit"                          
    ]
    global_iteration_components = [
        #"household",
        #"truck",
        #"prepare_network_highway", # TODO remove if it is not needed in global feedback
        #"highway",
        #"transit"
    ]
    final_components = []
    start_iteration = 1
    end_iteration = 1
