####################################
#     SCENARIO CONFIGURATION       #
####################################

[scenario]
    year = 2015
    verify = false
    landuse_file = "landuse/tazData.csv"
    landuse_index_column = "ZONE"
    landuse_index_in_network_column = "@taz_id"
    landuse_total_population_column = "TOTPOP"
    landuse_total_employment_column ="TOTEMP"
    landuse_total_acre_column = "TOTACRE"

[run]
    start_component = ""
    initial_components = [
        #"create_tod_scenarios",            # working
        #"active_modes",                    # runs in lasso
        "home_accessibility",              # working
        #"air_passenger",                   # not needed for BART, not tested
        #"prepare_network_highway",         # Working!!
        #"highway",                         # Working!!
        #"highway_maz_skim",                # not needed for BART, not tested
        #"prepare_network_transit",         # working
        #"transit"                          
    ]
    global_iteration_components = [
        #"household",                       # can be called from tm2py
        #"internal_external",               # not needed for BART, not tested
        #"truck",                           # Working!!
        #"highway_maz_assign",              # not needed for BART, not tested
        #"prepare_network_highway",         # Working!!
        #"highway",                         # Working!!
        #"prepare_network_transit",         # Working
        #"transit"
    ]
    final_components = []
    start_iteration = 0
    end_iteration = 1
    host_ip_address = "10.0.166.185"
