####################################
#     SCENARIO CONFIGURATION       #
####################################

[scenario]
    year = 2015
    verify = false
    landuse_file = "inputs/landuse/tazData.csv"
    landuse_index_column = "ZONE"
    landuse_index_in_network_column = "@taz_id"
    landuse_total_population_column = "TOTPOP"
    landuse_total_employment_column ="TOTEMP"
    landuse_total_acre_column = "TOTACRE"

[run]
    start_component = ""
    initial_components = [
        "create_tod_scenarios",
        "prepare_network_highway",
        "highway",
        "prepare_network_transit",
        "transit",
    ]
    global_iteration_components = [
        "home_accessibility",
         "household", 
         "truck",
         "highway",
         "transit",
         "convergence_report"
    ]
    final_components = []
    start_iteration = 0
    end_iteration = 3

    [run.warmstart]
        warmstart = true
        warmstart_check = true
        household_highway_demand_file = "warmstart/demand_matrices/highway/household/TAZ_Demand_{period}.omx"
        household_transit_demand_file = "warmstart/demand_matrices/transit/trn_demand_v9_trim_{period}.omx"
        air_passenger_highway_demand_file = "warmstart/demand_matrices/highway/air_passenger/2015_tripsAirPax{period}.omx"
        internal_external_highway_demand_file = "warmstart/demand_matrices/highway/internal_external/tripsIx{period}.omx"
        truck_highway_demand_file = "warmstart/demand_matrices/highway/commercial/tripstrk{period}.omx"
