####################################
#     SCENARIO CONFIGURATION       #
####################################

[scenario]
    year = 2015
    verify = false
    landuse_file = "inputs/landuse/tazData.csv"
    landuse_index_column = "ZONE"
    landuse_index_in_network_column = "@taz_id"
    landuse_total_population_column = "TOTPOP"
    landuse_total_employment_column ="TOTEMP"
    landuse_total_acre_column = "TOTACRE"

[run]
    start_component = ""
    initial_components = [
		#"create_tod_scenarios",
		#"prepare_network_highway",
		#"highway",
		#"prepare_network_transit",
		#"transit",
		#"convergence_report"		
    ]
    global_iteration_components = [
		"home_accessibility", # needs to be updated everytime after skims are updated
		"household", 
		#"truck",
		#"highway",
		#"transit",
		#"convergence_report"	
    ]
    final_components = []
    start_iteration = 1
    end_iteration = 1
	warmstart_check = false