####################################
#     SCENARIO CONFIGURATION       #
####################################

[scenario]
    year = 2015
    verify = false
    landuse_file = "inputs/landuse/maz_data.csv"
    landuse_index_column = 'ZONE'

[run]
    start_component = ""
    initial_components = [
        #"create_tod_scenarios",
        #"active_modes",
        "home_accessibility",
        "air_passenger",
        "prepare_network_highway",
        "highway",
        "highway_maz_skim",
        #"prepare_network_transit",
        #"transit_assign",
        #"transit_skim"
    ]
    global_iteration_components = [
        "household",
        "internal_external",
        "truck",
        "highway_maz_assign",
        "highway",
        #"prepare_network_transit",
        #"transit_assign",
        #"transit_skim"
    ]
    final_components = []
    start_iteration = 0
    end_iteration = 1
    host_ip_address = "10.0.143.35"
    ctramp_run_dir = 'C:\MTC_tmpy\TM2\2015_BaseY_P2Y2015'
	sample_rate_iteration = [0.50]
